FROM cgr.dev/chainguard/wolfi-base:latest@sha256:918a593b8268c222afd4e2c4f06860ac984e60719b4697e4c71d796bc8fcd042

# if you need a quicker turnaround, you can patch the image like the below,
# before the automated image build picks up the new CVE fixes (24-48 hours, usually)

# USER root
# RUN apk update && \
# apk add --upgrade --no-cache libssl3 libcrypto3

USER nonroot

