FROM cgr.dev/chainguard/wolfi-base:latest@sha256:1454fe554abc89f10a43cabc290d8d61941d7e81c9778b408894aaba27d398a1

# if you need a quicker turnaround, you can patch the image like the below,
# before the automated image build picks up the new CVE fixes (24-48 hours, usually)

# USER root
# RUN apk update && \
# apk add --upgrade --no-cache libssl3 libcrypto3

USER nonroot

