FROM cgr.dev/chainguard/wolfi-base:latest@sha256:a31344ab2cb8618db84f535eec56f76f6178b142cb92cb2e48676cc2dcebea72

# if you need a quicker turnaround, you can patch the image like the below,
# before the automated image build picks up the new CVE fixes (24-48 hours, usually)

# USER root
# RUN apk update && \
# apk add --upgrade --no-cache libssl3 libcrypto3

USER nonroot

