name: Auto-merge Renovate PRs

on:
  # Only trigger after other workflows complete
  workflow_run:
    workflows:
      - "Publish Base Docker images"
      - "Create Release Tag"
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    # Only run if the workflow that triggered us was successful
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Get PR details from workflow run
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            // Get the PR associated with this workflow run
            const workflow_run = context.payload.workflow_run;

            // Get PRs associated with the head commit
            const pulls = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: workflow_run.head_sha
            });

            if (pulls.data.length === 0) {
              console.log('No PR found for this workflow run');
              return null;
            }

            const pr = pulls.data[0];

            // Only process Renovate PRs
            if (pr.user.login !== 'renovate[bot]' && pr.user.login !== 'renovate') {
              console.log(`Skipping non-Renovate PR from ${pr.user.login}`);
              return null;
            }

            console.log(`Found Renovate PR #${pr.number}: ${pr.title}`);

            core.setOutput('number', pr.number);
            core.setOutput('title', pr.title);
            core.setOutput('mergeable_state', pr.mergeable_state);
            core.setOutput('draft', pr.draft);
            core.setOutput('node_id', pr.node_id);
            core.setOutput('found', 'true');

            return pr;

      - name: Check if PR should be auto-merged
        id: should_merge
        if: steps.pr.outputs.found == 'true'
        env:
          PR_TITLE: ${{ steps.pr.outputs.title }}
          PR_NUMBER: ${{ steps.pr.outputs.number }}
          MERGEABLE_STATE: ${{ steps.pr.outputs.mergeable_state }}
          IS_DRAFT: ${{ steps.pr.outputs.draft }}
        run: |
          echo "PR #$PR_NUMBER: $PR_TITLE"
          echo "Mergeable state: $MERGEABLE_STATE"
          echo "Draft: $IS_DRAFT"

          # Don't merge drafts
          if [ "$IS_DRAFT" = "true" ]; then
            echo "should_merge=false" >> $GITHUB_OUTPUT
            echo "reason=PR is in draft state" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Auto-merge criteria (based on renovate.json rules)
          SHOULD_MERGE=false
          REASON=""

          # Digest updates (immediate merge)
          if echo "$PR_TITLE" | grep -qi "digest"; then
            SHOULD_MERGE=true
            REASON="Digest-only update (low risk)"

          # Patch/minor updates for GitHub Actions
          elif echo "$PR_TITLE" | grep -qiE "update .*(action|workflow).*to v[0-9]+\.[0-9]+"; then
            SHOULD_MERGE=true
            REASON="GitHub Actions patch/minor update"

          # Patch updates for Docker images
          elif echo "$PR_TITLE" | grep -qiE "update .*(docker|image)"; then
            if ! echo "$PR_TITLE" | grep -qiE "to v[0-9]+\.0\.0|major"; then
              SHOULD_MERGE=true
              REASON="Docker image patch/minor update"
            else
              REASON="Major update requires manual review"
            fi

          # Major version updates - never auto-merge
          elif echo "$PR_TITLE" | grep -qiE "major|to v[0-9]+\.0\.0"; then
            REASON="Major update requires manual review"

          else
            REASON="Update type not recognized for auto-merge"
          fi

          echo "should_merge=$SHOULD_MERGE" >> $GITHUB_OUTPUT
          echo "reason=$REASON" >> $GITHUB_OUTPUT
          echo "Decision: $REASON"

      - name: Enable GitHub auto-merge
        if: steps.pr.outputs.found == 'true' && steps.should_merge.outputs.should_merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // Enable GitHub's native auto-merge feature
            // This will automatically merge the PR when all checks pass
            try {
              await github.graphql(`
                mutation($pullRequestId: ID!) {
                  enablePullRequestAutoMerge(input: {
                    pullRequestId: $pullRequestId,
                    mergeMethod: SQUASH
                  }) {
                    pullRequest {
                      id
                      autoMergeRequest {
                        enabledAt
                      }
                    }
                  }
                }
              `, {
                pullRequestId: '${{ steps.pr.outputs.node_id }}'
              });

              console.log('✅ Auto-merge enabled - PR will merge when all checks pass');

              // Add a comment to explain what happened
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ steps.pr.outputs.number }},
                body: '✅ **Auto-merge enabled**\n\nReason: ${{ steps.should_merge.outputs.reason }}\n\nThis PR will automatically merge when all required checks pass.'
              });
            } catch (error) {
              console.error('Failed to enable auto-merge:', error);
              core.setFailed(`Could not enable auto-merge: ${error.message}`);
            }

      - name: Comment on PR (if not auto-merged)
        if: steps.pr.outputs.found == 'true' && steps.should_merge.outputs.should_merge == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr.outputs.number }},
              body: '⏸️ **Auto-merge skipped**\n\nReason: ${{ steps.should_merge.outputs.reason }}\n\nThis PR requires manual review and approval.'
            });
