name: Auto-approve Renovate PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'renovate'
    steps:
      - name: Auto-approve Renovate PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;

            console.log(`Approving PR #${pull_number} from ${context.actor}`);

            await github.rest.pulls.createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE',
              body: 'Auto-approved by workflow'
            });

            console.log(`✅ Successfully approved PR #${pull_number}`);
